### ISSUE TITLE
error in extension repository

### ISSUE THREAD

**Issue by fritzmg** [markocupic/rotate_image#1]
When this extension is installed from [the extension repository](https://contao.org/de/erweiterungsliste/view/rotate_image.html), it will be installed into the wrong directory. The directory's name will be `rotate_image`, but it is supposed to be `mcupic_rotate_image`.

**Comment by markocupic** [comment]
Oh I see. Please check now.

**Comment by fritzmg** [comment]
I see you have changed the PHP files now accordingly. Though shouldn't the version in the ER2 now also be  `1.0.6`?

**Comment by markocupic** [comment]
Yes, you're right. I've corrected it just now.
