### ISSUE TITLE
extension not showing in backend

### ISSUE THREAD

**Issue by vmcgiov** [markocupic/rotate_image#2]
Hey there,

the extension does not seem to install correctly. files are in vendor folder, no contao database update after installation, no icons showing in backend to rotate images. ImageMagic is activated on the server. Contao Version 4.4.47. Installed with contao-manager.

is this a known issue? Any idea what causes this problem?

**Comment by markocupic** [comment]
Under contrao 4.9 everything works how it should.

Is there an error if you open the console of your browser?

**Comment by vmcgiov** [comment]
No error unfortunately.

Just to be clear: The rotation icons should appear in the file-manager I guess? (I havent found any documentation or information about where it is supposed to show up).

**Comment by vmcgiov** [comment]
I just tried to install it on a different contao installation with 4.9. I can confirm that it works perfectly with that version. Problem seems to be with 4.4..

**Comment by markocupic** [comment]
Any errors in the cobsole of your browser?

**Comment by markocupic** [comment]
No error unfortunately.

Just to be clear: The rotation icons should appear in the file-manager I guess? (I havent found any documentation or information about where it is supposed to show up).

Yes, the icon should appear in the file manager as an operation like edit or delete.


--------------------------------------
Marko Cupic
Surenweidstr. 2
CH-6208 Oberkirch

http://4ae-racing-team.ch
http://kletterkader.com

 
 

Gesendet: Montag, 30. März 2020 um 13:12 Uhr
Von: "vmcgiov" <notifications@github.com>
An: markocupic/rotate_image <rotate_image@noreply.github.com>
Cc: "Marko Cupic" <m.cupic@gmx.ch>, Comment <comment@noreply.github.com>
Betreff: Re: [markocupic/rotate_image] extension not showing in backend (#2)


 

No error unfortunately.

Just to be clear: The rotation icons should appear in the file-manager I guess? (I havent found any documentation or information about where it is supposed to show up).

**Comment by vmcgiov** [comment]
> 
> Any errors in the cobsole of your browser?

zero errors.. do you have the possability to check your plugin with an 4.4 installation to see if you can reproduce my problem?

**Comment by markocupic** [comment]
No I've got no contao 4.4 installation for debugging.

**Comment by vmcgiov** [comment]
I just checked it on a second 4.4 installation too. same problem. first 4.4 was with a eclipse premium theme. second one with rocksolid. same problem with both installations.

**Comment by markocupic** [comment]
The error should be fixed in version 1.0.18. Please try it out.

**Comment by vmcgiov** [comment]
> 
> 
> The error should be fixed in version 1.0.18. Please try it out.

The error is indeed fixed with 1.0.18! Thank you very much for your help and time. stay safe!

**Comment by markocupic** [comment]
Same to you. ;-)
